site_name: Documentation
repo_url: 'https://github.com/SoFairOA/documentation'
edit_uri_template: 'blob/main/docs/{path}'
nav:
  - Home: index.md
theme: readthedocs
markdown_extensions:
  - codehilite:
      guess_lang: false
  - admonition
  - footnotes
plugins:
    - mermaid2
extra_css:
  - css/extra.css
extra_javascript:
  - js/clipboard.min.js
  - js/extra.js
