site_name: Documentation
repo_url: 'https://github.com/SoFairOA/documentation'
edit_uri_template: 'blob/main/docs/{path}'
nav:
  - Home: index.md
  - 'Foreword': 01-foreword.md
  - 'Introduction': 02-introduction.md
  - 'Scope': 03-scope.md
  - 'Workflow': 04-workflow.md
  - 'Step 1: Sharing': 11-step-1.md
  - 'Step 2: Deposit': 12-step-2.md
  - 'Step 3: Extracted mention': 13-step-3.md
  - 'Step 4: Notification': 14-step-4.md
  - 'Step 5: Validation': 15-step-5.md
  - 'Step 6: Saving': 16-step-6.md
  - 'Step 7: Archiving': 17-step-7.md
  - 'Step 8: Identification': 18-step-8.md
  - 'Step 9: Metadata deposit metadata': 19-step-9.md
  - 'Annex A: Bibliography': A-bibliography.md
theme: readthedocs
copyright: Copyright &copy; 2024 SoFAIR Contributors.
markdown_extensions:
  - codehilite:
      guess_lang: false
  - admonition
  - footnotes
plugins:
  - mermaid2
  - search
extra_css:
  - css/extra.css
extra_javascript:
  - js/clipboard.min.js
  - js/extra.js
